- hosts: localhost
  roles: 
    - storefront-provision

- hosts: "tag_Name_{{ storefront_instance_name }}"
  vars: 
    ansible_ssh_private_key_file: "{{ ssh_key_filepath }}"
  roles:
    - storefront-deploy
