version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout -t 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
      - cd orderservice
      - export VERSION_NUM=$(python nextver.py iacf_order_service $MAJOR $MINOR)
      - echo $VERSION_NUM
      - ./build.sh
      - ./build_image.sh $VERSION_NUM
      - source ./tag_push.sh $VERSION_NUM