AWSTemplateFormatVersion: 2010-09-09
Description: Resources for iacfreedom platform to make use of.

Resources:

  IACFreedomArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "{{ iacfreedom_artifact_bucket }}"

  IACFreedomBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "iacFreedomBuildRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal: { "Service": "codebuild.amazonaws.com" }

  IACFreedomBuildPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "iacFreedomBuildPolicy"
      Roles:
        - !Ref IACFreedomBuildRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: 
              - "s3:PutObject"
            Resource:
              - "arn:aws:s3:::bin-iacfreedom/*"
          - Effect: "Allow"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource:
              - "arn:aws:logs:*:*:log-group:/aws/codebuild/orderServiceBuildTaskCF"
              - "arn:aws:logs:*:*:log-group:/aws/codebuild/orderServiceBuildTaskCF:*"
          - Effect: "Allow"
            Action:
              - "ecr:GetAuthorizationToken"
              # - "ecr:BatchGetImage"
              # - "ecr:GetDownloadUrlForLayer"
              # - "ecr:BatchCheckLayerAvailability"
            Resource:
              - "*"

  IACFreedomGoSvcBuilderImageRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "golang_svc_buildenv"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "ecr:BatchGetImage"
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchCheckLayerAvailability"
            Principal: { "Service": "codebuild.amazonaws.com" }

  IACFreedomOrderServiceBuildTask:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: orderServiceBuildTaskCF
      ServiceRole: !Ref IACFreedomBuildRole
      Source:
        Type: "github"
        Location: "https://github.com/adamkrieger/iacfreedom.git"
        BuildSpec: "./orderservice/buildspec.build.yml"
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Type: "LINUX_CONTAINER"
        Image: !Sub "${AWS::AccountId}.dkr.ecr.us-east-1.amazonaws.com/golang_svc_buildenv:1.11"
        PrivilegedMode: true
      Artifacts:
        Type: "NO_ARTIFACTS"

####################################
### Order Service Infrastructure ###
####################################

  IACFreedomOrderServiceImageRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "iacf_order_service"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
            Principal: { "Service": "codebuild.amazonaws.com" }